import json

replacements = {
    1: "Chapter 7",
    2: "When I returned, I found the following letter from my father:",
    3: "\"To my dear Victor,",
    4: "\"You have probably waited anxiously for a letter stating the date of your return to us. I, too, was initially tempted to write just a few lines mentioning the day I would wait for you to return. But that would be a cruel kindness, and I couldn't bring myself to do it.",
    5: "My dear son, how surprised would you be if you expected a happy and joyful welcome, but instead faced tears and despair? And, Victor, how should I tell you about our misfortune?",
    6: "Your long absence cannot have made you numb to our joys and sorrows, and how can I bring pain to my son who has been away for so long? I want to prepare you for this terrible news, but I know it is impossible. Even at this moment, your eyes must be scanning the letter to find the words that will convey this terrifying news.",
    7: "\"William is dead! That lovely child, whose smile alone delighted and warmed my heart, who was so gentle yet so cheerful! Victor, he has been murdered!",
    8: "\"I will not try to comfort you. I will simply relate the circumstances of what happened that day.",
    9: "\"Last Thursday, May 7th, I, your cousin, and your two brothers went for a walk in Plainpalais. The evening air was warm and peaceful, and we extended our walk further than usual.",
    10: "It was already after sunset and dusk had fallen when we thought of returning, and only then did we realize that William and Ernest, who had gone ahead, were nowhere to be seen. So we decided to sit on a bench and rest until the children returned.",
    11: "Eventually, Ernest came back and asked if we had seen his brother. He said he had been playing with him, but William had run away to hide, and though he searched everywhere, he couldn't find him; he waited for a long time, but William never appeared.",
    12: "\"That account frightened us, and we continued searching for him until late into the night. Elizabeth guessed that he might have returned home first.",
    13: "But the child was not at home. We went out again with torches.",
    14: "I could not just sit still at the thought of my lovely child being lost and exposed to the cold dampness and dew of the night. Elizabeth also suffered from extreme agony.",
    15: "Around five in the morning, I found my lovely child, who had been glowing and energetic just the night before, lying pale and stiff on the grass. The murderer's handprints were clearly left on his neck.",
    16: "\"The child was brought home, and Elizabeth discovered the secret upon seeing the clear agony on my face. She insisted strongly on seeing the body.",
    17: "At first I tried to stop her, but she was stubborn, and as soon as she entered the room where the body was laid, she urgently checked the victim's neck, clasped her hands together, and cried out, 'Oh, God! I have killed the child I love!'",
    18: "\"She fainted, and only woke up after extreme difficulty. Even after waking, she spent her time only with tears and sighs.",
    19: "She told me that just that evening, William had begged her to give him a very valuable miniature portrait of your mother that she possessed. That portrait is gone, and it must surely have been what tempted the murderer to commit the crime. Right now, there is no trace of the culprit.",
    20: "Although our search to find him continues restlessly, it won't bring my beloved William back to life!",
    21: "\"Come, my dear Victor. You are the only one who can comfort Elizabeth. She cries endlessly and unfairly blames herself for the child's death.",
    22: "The child's words pierce my heart. We are all unhappy. But my son, wouldn't that be another reason why you must return and become our comforter?",
    23: "Your beloved mother! Ah, Victor! I now say that I thank God she is not alive to witness the cruel and miserable death of her youngest son!",
    24: "\"Come, Victor. Do not come consumed by a desire for revenge against the assassin, but with a peaceful and gentle heart that will heal the wounds in our hearts instead of letting them fester.",
    25: "Enter this house of mourning, my friend. Not with hatred for the enemy, but with kindness and affection for those who love you.",
    26: "\"Your loving and grieving father,",
    27: "\"Alphonse Frankenstein.",
    28: "\"Geneva, May 12th, 17--.\"",
    29: "Clerval, who watched my face while I read this letter, was shocked to see the joy I showed upon first receiving news from my friends instantly turn to despair. I threw the letter on the table and covered my face with my two hands.",
    30: "\"My dear Frankenstein,\" Henry cried out upon seeing me weeping bitterly. \"Must you always be unhappy? My dear friend, what on earth has happened?\"",
    31: "Pacing the room in an uncontrollable state of excitement, I motioned for him to pick up the letter. Tears poured from Clerval's eyes as he read down the news of my misfortune.",
    32: "\"My friend, no words can offer comfort,\" he said. \"Your disaster is irreversible. What do you intend to do now?\"",
    33: "\"I must go to Geneva immediately. Come with me, Henry. I need to get horses to ride.\"",
    34: "While we walked, Clerval tried to offer words of comfort. He could only express his sincere sympathy. \"Poor William!\" he said.",
    35: "\"The lovely child now sleeps beside his angelic mother! Anyone who had seen his dazzling and bright youthful beauty could not help but shed tears over his premature death! To die so terribly, to feel the grasp of a murderer!",
    36: "What a terrible murderer to destroy such radiant innocence! Poor little boy! The only comfort left for us is that while his friends grieve and cry, the child has found peaceful rest.",
    37: "The moment of agony has passed, and his suffering is over forever. A mound of dirt covers his fragile body, so the child will no longer know any pain. The child is no longer an object of pity.",
    38: "Pity must be saved for the miserable survivors left behind.\"",
    39: "Clerval spoke like this as we hurriedly escaped the streets. Those words were deeply engraved in my heart, and I would often recall them later when I was alone. But for now, as soon as the horses arrived, I hurried into the two-wheeled carriage and bid farewell to my friend.",
    40: "My journey was extremely gloomy. At first, I just wanted to hurry back out of a desire to comfort my loving and grieving family and share their pain. But as I drew closer to my hometown, I slowed my steps.",
    41: "It was because I could not handle the multitude of emotions rushing into my heart. I passed by scenery that was familiar to my childhood but which I had not seen for almost six years. How much everything must have changed during that time!",
    42: "A sudden and horrific change had occurred once, but a thousand small circumstances might have created other changes little by little. Even if those changes happened more quietly, they could be just as decisive.",
    43: "Fear overwhelmed me. Unable to define what it was, I was so afraid of the countless nameless disasters that made me tremble that I dared not take another step forward.",
    44: "I stayed in Lausanne for two days in this painful state of mind. I looked at the lake. The waves were calm, everything around was perfectly still, and the snow-covered mountains, the 'palaces of nature,' remained unchanged.",
    45: "Gradually, the peaceful and holy scenery calmed my mind, and I continued my journey toward Geneva.",
    46: "The road ran along the lake, and the lake grew narrower as I neared my hometown. I could see the black slopes of the Jura Mountains and the shining peaks of Mont Blanc more clearly. I cried like a child.",
    47: "\"Dear mountains! My beloved, beautiful lake! How do you welcome a wanderer? Your peaks are clear, and the sky and lake are blue and calm. Does this foretell peace, or does it mock my misery?\"",
    48: "My friend, I worry that dwelling too long on these introductory circumstances will bore you, but those were relatively happy days, and I recall them with joy. My country, my beloved country! Who but a native could know the joy of seeing your streams, your mountains, and above all, your beautiful lake again!",
    49: "However, as I got closer to home, sadness and fear overwhelmed me once more. Night surrounded me from all sides, and as the dark mountains became nearly invisible, my mood grew even gloomier.",
    50: "The landscape looked like a massive, faint stage of evil, and I dimly foresaw that I was destined to become the most miserable being among humans. Ah! My prophecy was correct.",
    51: "If there was only one thing wrong, it was the fact that, even amid all the misery I imagined and feared, I failed to grasp even a hundredth of the predestined pain I would have to endure.",
    52: "By the time I arrived in the outskirts of Geneva, it was completely dark everywhere. The city gates were already firmly closed, and I had to spend the night in a village called Secheron, half a league from the city. The sky was clear, and I absolutely could not rest, so I decided to visit the place where poor William was murdered.",
    53: "Since I could not pass through the city, I had to cross the lake by boat to get to Plainpalais. During this short voyage, I saw lightning strike in the most beautiful shapes on the summit of Mont Blanc. A storm seemed to be approaching fast, and upon landing, I climbed a low hill to watch its progress.",
    54: "As the storm approached, the sky was covered with dark clouds, and soon thick raindrops began to fall slowly before suddenly pouring down fiercely.",
    55: "I got up from my seat and kept walking. The darkness and the storm grew fiercer by the minute, and thunder burst above my head with a terrifying roar. The sound echoed across Mount Salève, the Jura Mountains, and the Savoy Alps. The flashing lightning blinded me and illuminated the lake, making it look like a massive sea of fire. Then, for a moment, everything was plunged into pitch-black darkness, and soon my eyes recovered from the previous flash.",
    56: "As is often the case in Switzerland, the storm appeared simultaneously in multiple parts of the sky. The most violent storm stayed just north of the village, over the lake between the Belrive peninsula and the village of Copet. Another storm illuminated the Jura Mountains with faint flashes, and another storm made the Mole, a peaked mountain east of the lake, go dark or occasionally reveal its form.",
    57: "Watching this beautiful yet terrifying storm, I hurried my steps. This majestic war in the sky uplifted my heart. I brought my two hands together and cried out loudly. \"William, my dear angel! This is your funeral, this is your requiem!\" The moment I spat out these words, I saw a figure sneaking out from behind a pile of trees near me in the darkness. I froze in place and stared intently. My eyes could not be mistaken.",
    58: "A flash of lightning illuminated the object and clearly revealed its shape to me. That massive build and the deformed appearance, too hideous to be called human, instantly informed me that it was the terrible, filthy demon I had given life to. What on earth was he doing there? Could he be the murderer who killed my brother? I shuddered just thinking about it.",
    59: "The moment that thought crossed my mind, I was convinced it was true. My teeth chattered, and I could hardly stand, forcing me to lean against a tree. The figure brushed past me quickly and soon vanished into the darkness. No being in human form could have destroyed that beautiful child. He was the murderer!",
    60: "I had no room for doubt. The mere occurrence of that thought was the undeniable proof of the fact. I considered chasing the demon, but it was useless. When the next lightning struck, I saw him climbing among the rocks of the steep, almost vertical Mount Salève, which forms the southern border of Plainpalais.",
    61: "He quickly reached the summit and vanished from sight.",
    62: "I stood motionless, unable to move a muscle. The thunder stopped, but the rain kept falling, and the surroundings were wrapped in an impenetrable darkness. I recounted in my head the events I had tried so hard to forget until now.",
    63: "The entire process leading up to creating the creature, the appearance of the creature I made with my own hands standing by my bedside, and his escape. Nearly two years have already passed since the night he first gained life, and is this his first crime?",
    64: "Ah! I have unleashed a depraved villain who enjoys slaughter and misfortune into this world. Was it not him who killed my brother?",
    65: "No one could imagine the suffering I endured during the rest of the time I spent outdoors, soaking in the cold and rain all night. But I did not even feel the discomfort of the weather. My imagination was entirely captivated by scenes of evil and despair.",
    66: "When I thought of the being I threw among humanity, endowing it with the will and power to execute terrible purposes like the act it just committed, it felt like my own vampire, my own soul, released from the grave and forced to destroy everything I love.",
    67: "Dawn broke, and I turned my steps to walk toward the city. The city gates were open, and I hurried to my father's house. The very first thought that came to me was that I must reveal what I knew about the murderer and initiate an immediate pursuit.",
    68: "But considering the story I had to confess, I had to hesitate. The story that I met the being I sculpted and gave life to with my own hands in the middle of the night on a steep cliff of an impassable mountain.",
    69: "Furthermore, I also remembered the nervous fever that struck me right around the time I thought I made the creature. That fever only added a touch of delusion to an already absurd story. If someone else had told me such a story, I knew perfectly well that I too would have dismissed it as the nonsense of a lunatic.",
    70: "Besides, even if people believed my words and I convinced my family to start a pursuit, the beast's bizarre nature would clearly let it evade all tracking. And what use would a pursuit be anyway? Who on earth could catch that monster capable of climbing the sheer slopes of Mount Salève?",
    71: "Reaching these thoughts, I made up my mind and decided to keep silent.",
    72: "It was around five in the morning when I entered my father's house. I instructed the servants not to wake the family, and went into the study to wait for their usual waking hour.",
    73: "Six years had passed. Except for one indelible trace, it was a time that flew by like a mere dream, and I stood in the exact same spot where I had last hugged my father before leaving for Ingolstadt. My beloved and respected father! He was still by my side.",
    74: "I looked at my mother's portrait placed above the fireplace mantel. In that historical painting, commissioned by my father, Caroline Beaufort was kneeling by her dead father's coffin, lost in deep agony of despair. She wore plain clothes and had pale cheeks, but a dignity and beauty that seemed to forbid even sympathy lingered.",
    75: "Below this painting was a miniature portrait of William, and tears flowed from my eyes looking at it. While I stood there like this, Ernest came in. He had heard me arrive and hurried out to welcome me. \"Welcome back, my dear brother Victor,\" Ernest said. \"Ah!",
    76: "If only you had come three months earlier, you could have seen all of us full of joy and delight. You have come to us only now to share in this terrible misfortune where nothing offers comfort. But thanks to your arrival, our father, who has been collapsing under this misfortune, will be able to regain his strength. And if you persuade her well, you can also stop poor sister Elizabeth's futile and painful self-blame. Poor William! He was our love and our pride!\"",
    77: "Tears poured uncontrollably from my brother's eyes, and a pain like death wrapped around my entire body. Until then, I had only pictured the devastation of our empty home in my mind, but now the reality struck me as a new and by no means light disaster. Trying to calm Ernest down, I asked for more details about my father, and then I brought up our cousin's name.",
    78: "\"More than anyone, sister Elizabeth,\" Ernest said. \"needs comfort. She is blaming herself, saying William's death is her fault, and because of that she is very miserable. But since the murderer was revealed...\"",
    79: "\"The murderer has been revealed! My God!",
    80: "How can that be? Who dared even attempt to pursue him?",
    81: "That is impossible. It would be better to try catching up with the wind or blocking a mountain stream with a straw.",
    82: "I saw him too. He was freely on the loose just last night!\"",
    83: "\"I don't know what you mean,\" my brother answered in a puzzled voice. \"But to us, that discovery has driven us completely to the bottom of misfortune. At first, no one wanted to believe that fact, and even sister Elizabeth still refuses to believe it despite all the evidence that has come out.",
    84: "After all, who would believe that Justine Moritz, who was so kind and followed all our family so well, could commit such a terrible and creepy crime overnight?\"",
    85: "\"Justine Moritz! The poor, poor girl, Justine is the suspect? But that is a misunderstanding.",
    86: "Everyone knows that. No one believes it, right, Ernest?\"",
    87: "\"No one believed it at first. But as various circumstances continuously surfaced, we were inevitably forced to believe it. Moreover, Justine's own attitude showed clear signs of extreme panic, adding weight to the evidence revealed as facts. Unfortunately, there seems to be no room for doubt. But there will be a trial today, so you will hear everything then too.\"",
    88: "Then Ernest told me the story that on the morning poor William's death was discovered, Justine had fallen ill and was bedridden for several days. Meanwhile, one of the servants was looking at the clothes Justine wore on the night of the murder, and found my mother's portrait, presumed to be the killer's motive, in her pocket.",
    89: "The servant immediately showed it to another servant, and without telling anyone in the family, the two went to the magistrate. And based on their testimony, Justine was arrested. When Justine was interrogated about the charges, she showed signs of extreme panic, which resulted in solidifying the suspicion against the poor girl.",
    90: "It was a bizarre story, but my faith did not waver. I answered firmly.",
    91: "\"You are all mistaken. I know who the murderer is. Justine, poor and good Justine, is innocent.\"",
    92: "Right at that moment, my father walked in. Deep sorrow heavily stained his complexion, but he tried to greet me joyfully. After we exchanged sorrowful greetings, my father tried to bring up another topic instead of talking about our disaster, but at that moment, Ernest cried out.",
    93: "\"My God, father! Brother Victor says he knows who the murderer that killed poor William is.\"",
    94: "\"We know too, unfortunately.\" my father answered. \"I would rather have stayed ignorant forever than to discover such corruption and ingratitude in the child I cared for so deeply.\"",
    95: "\"Father, you are mistaken. Justine is innocent.\"",
    96: "\"If she is innocent, God will never allow her to suffer as a sinner. Her trial is being held today, and I too sincerely hope and pray that she is released with a not-guilty verdict.\"",
    97: "At my father's words, I felt relieved. I firmly believed in my heart that Justine, as well as any human being, was innocent of this murder.",
    98: "Therefore, I felt no fear thinking that no circumstantial evidence strong enough to convict her would be presented. My story was not the kind that could be revealed publicly. Its shocking gruesomeness would only be considered a lunatic's nonsense by worldly people.",
    99: "Without directly confirming it with their own senses, who else but me, the creator, would ever believe in the existence of the living monument of arrogance and reckless ignorance that I unleashed into the world?",
    100: "Soon, Elizabeth joined us. Since the last time I saw her, time had transformed her greatly. Time bestowed upon her a loveliness that surpassed the beauty of her childhood.",
    101: "There was the same innocence and liveliness as before, but a facial expression revealing deeper sensitivity and intellect blended with them. She welcomed me with the utmost affection. \"My dear cousin, now that you are here,\" she said.",
    102: "\"I have hope. You might be able to find a way to prove the innocence of our poor, guiltless Justine. Ah!",
    103: "If she is convicted, who would be safe? I am as certain of her innocence as I am of my own. Our misfortune is doubly hard on us.",
    104: "Not only have we lost that lovely and precious child, but this poor girl whom I sincerely love is also in danger of being taken away by a more terrible fate. If she is convicted, I will never know joy again. But she will not be convicted.",
    105: "I am sure of it. If that happens, even after our little William's sad death, I will be able to be happy again.\"",
    106: "\"She is innocent, my Elizabeth.\" I said. \"And that fact will soon be proven. Fear nothing. Be completely assured that she will be released innocent and stay strong.\"",
    107: "\"You are so kind and generous! Everyone else believes she is guilty, and because of that I was deeply distressed. I know it is impossible for her to be guilty. Seeing all the other people caught up in such deadly prejudice just left me hopeless and bleak.\" She shed tears.",
    108: "\"My dearest niece,\" my father said. \"Dry your tears. If she is innocent as you believe, trust in the fairness of our law, and that I will actively step in to ensure not a single bit of bias intervenes.\""
}

with open('c:/git_repo/Book_apps/frankenstein/src/main/assets/books/ch_11.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for chunk in data:
    chunk_id = chunk['id']
    if chunk_id in replacements:
        chunk['en'] = replacements[chunk_id]

with open('c:/git_repo/Book_apps/frankenstein/src/main/assets/books/ch_11.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
