import json

new_en = [
    "Chapter 20",
    "One evening I sat in my laboratory. The sun had set and the moon was just rising above the sea. I did not have enough light to work, so I sat still, pausing to consider whether I should stop my work for the night or continuously focus to speed up its completion. As I sat there, a series of thoughts came to mind, and I began to think about the consequences of what I was doing right now.",
    "Three years ago, I worked in the same way and created a monster whose unmatched cruelty ruined my heart and filled it forever with the bitterest regret. I was now trying to create another being whose nature I knew nothing about. She might become ten thousand times more evil than her mate and enjoy murder and misery for their own sake.",
    "He had sworn to leave human settlements and hide in the desert, but she had not. She, who would most likely become a thinking and rational animal, might refuse to follow a promise made before she was even created. They might even hate each other. The creature who was already alive hated his own ugliness, so wouldn't he feel an even greater disgust when it appeared right before his eyes in female form?",
    "She might also feel disgusted by him and turn to the superior beauty of humans. She might leave him, and he could be left alone again, furious at the new insult of being abandoned by a creature of his own kind.",
    "Even if they left Europe and lived in the deserts of the new world, one of the first results of the companionship the monster craved would be children, and a race of monsters might reproduce on earth, putting the very survival of humanity in a dangerous and terrifying state. Did I have the right to bring this curse upon endless future generations just for my own benefit?",
    "In the past, I had been swayed by the monster's twisted logic and left stunned by his evil threats, but now, for the first time, the wickedness of my promise rushed over me. I shuddered at the thought that future generations might curse me as a disaster to humanity, because my selfishness did not hesitate to buy my own peace at the cost, perhaps, of the survival of the entire human race.",
    "When I looked up and saw the monster standing by the window in the moonlight, I trembled and my heart seemed to sink. A terrifying smile wrinkled his lips as he watched me sit and perform the task he had assigned to me. Yes, he had followed me on my journey.",
    "He had wandered through the woods, hidden in caves, or taken shelter on wide, empty wastelands, and had now come to check on my progress and demand that I keep my promise.",
    "When I looked at him, his face was filled with extreme malice and a sense of betrayal. I thought of my promise to create another being like him with a maddening feeling, and trembling with passion, I tore what I was working on into pieces.",
    "The monster saw me destroy the creature on whose future existence he relied for his happiness, and he backed away with a howl of demonic despair and revenge.",
    "A demonic laugh came back as an answer through the moonlight. The sound echoed long and heavily in my ears, the mountains echoed it back, and I felt as if all of hell was surrounding me with mockery and laughter. Surely at that moment I should have been seized by madness and ended my miserable life, but my vow was delivered and I was left behind for a destiny of lingering pain.",
    "A few hours passed, and I stayed by the window staring at the sea. The wind died down and the sea was nearly motionless, and all of nature was resting under the eyes of the quiet moon. Only a few fishing boats floated here and there on the water, and occasionally a gentle breeze carried the sound of fishermen calling out to each other.",
    "I was feeling the silence without really noticing its extreme depth, when the sound of rowing near the shore suddenly caught my ear, and someone landed close to my house.",
    "A few minutes later, I heard my door creak as if someone was trying to open it quietly. I trembled from head to toe. I sensed who it was, and I wanted to wake up one of the farmers living in a cabin not far from my house, but I was overwhelmed by the helplessness I often feel when trying in vain to escape an impending danger in a terrible dream, and I froze in place.",
    "Soon, footsteps were heard along the hallway. The door opened and the terrible monster I feared appeared. He closed the door, approached me, and spoke in a suppressed voice.",
    "\"You have destroyed the work you started. What on earth do you intend to do? How dare you try to break your promise?",
    "I have endured hardship and misery. I left Switzerland with you, and crawled along the banks of the Rhine, between the willow islands, and over the tops of those hills. I lived for months among the moors of England and the wastelands of Scotland.",
    "I have endured unimaginable exhaustion, cold, and hunger, yet how dare you try to destroy my hope?\"",
    "\"Get out right now! I will break my promise. I will never create another being exactly as ugly and evil as you.\"",
    "\"Slave, I tried to persuade you with reason before, but you have proven yourself unworthy of my mercy. Remember that I have power. You may believe you are miserable, but I can make you so miserable that you will come to hate even the light of day.",
    "You are my creator, but I am your master. Obey me!\"",
    "Very well. I will go. But remember, I will be with you on your wedding night.",
    "I jumped forward and shouted. \"You villain! Before you sign my death sentence, make sure you yourself are safe first.\"",
    "\"Devil, stop. And do not pollute the air with this malicious noise. I have declared my resolve to you, and I am not a coward who will give in to words.",
    "Leave me. My mind will not be changed.\"",
    "\"Very well. I will go. But remember, I will be with you on your wedding night.\"",
    "I leaped forward and shouted. \"Villain! Before you sign my death warrant, make sure your own life is safe.\"",
    "I tried to grab him, but he dodged me and hurriedly left the house. A moment later I saw him get into a boat, and the boat shot across the water with the speed of an arrow before quickly disappearing into the waves.",
    "Everything became quiet again, but his words lingered in my ears. I burned with a rage to chase down the murderer of my peace and push him into the sea. Agitated, I hurriedly paced around the room, and my imagination created thousands of illusions to torment and stab me.",
    "Why didn't I chase after him and engage in a life-or-death struggle? But I let him leave, and he headed toward the mainland. I shuddered at the thought of who would be the next victim to fall to his insatiable thirst for revenge.",
    "And I remembered his words again. \"I will be with you on your wedding night.\" If so, that was the exact time set for my destiny to be fulfilled.",
    "At that time, I would die, and at the same time satisfy and extinguish his malice. That expectation did not bring me fear. But when I thought of my beloved Elizabeth, and the tears and endless sorrow she would shed when she found out her lover was so savagely snatched away from her, tears flowed from my eyes for the first time in months, and I swore I would not fall before my enemy without a fierce fight.",
    "The night passed and the sun rose from the sea. If the violence of anger sinking into the abyss of despair could be called calmness, my emotions had become calmer. I left the house, the terrible scene of last night's argument, and walked along the beach, treating the sea as an insurmountable barrier between myself and my own kind. No, in fact, a desire for it to be a barrier seeped into me.",
    "I hoped to spend the rest of my life on this barren rock, uninterrupted by the sudden shocks of misfortune, even if it meant a grueling existence. If I were to return, it would only be to become a sacrifice, or to watch the people I loved most die at the hands of the demon I had created myself.",
    "I wandered the island like a restless ghost, separated from everything I loved and made miserable by that parting. When noon came and the sun rose higher, I lay on the grass and was overcome by a deep sleep. I had been awake all through the previous night, my nerves were on edge, and my eyes were bloodshot from staying up all night and suffering.",
    "The sleep I fell into now refreshed me. When I woke up, I felt like I belonged to the human world again, and I began to look back on what had happened with greater composure. However, the monster's words still rang in my ears like a death knell. They felt like a dream, yet were as clear and oppressive as reality.",
    "The sun had gone down considerably, and I was still sitting on the beach, soothing my starving appetite with oat bread. Just then, I saw a fishing boat land near me, and one of the men brought me a package. It contained letters from Geneva and a letter from Clerval begging me to join him.",
    "He said he was wasting his time where he was, and had received letters from friends he made in London asking him to return to conclude the negotiations they started for their Indian business. He could no longer delay his departure. However, since a long voyage might follow his journey to London sooner than he currently guessed, he begged me to spend as much time with him as I could.",
    "Therefore, he begged me to leave my solitary island, meet him in Perth, and head south together. This letter brought me back to life to some extent, and I decided to leave my island after two days.",
    "But there was one task I had to do before I left, which made me shudder just thinking about it. I had to pack my chemical tools, and to do that, I had to enter the room that had been the scene of my disgusting work, and I had to touch those tools that made me sick just looking at them. The next morning at dawn, I gathered enough courage and opened the door to the laboratory.",
    "The remains of the half-finished creature I had destroyed were scattered on the floor, and I felt as if I had hacked away at the flesh of a living human. I paused for a moment to compose myself before entering the room.",
    "I moved the tools out of the room with trembling hands, but it occurred to me that I shouldn't leave behind the relics of my work to incite fear and suspicion among the farmers. Accordingly, I decided to put them in a basket with a large amount of stones, set them aside, and throw them into the sea that very night. Meanwhile, I sat on the beach and absorbed myself in cleaning and organizing my chemical equipment.",
    "Nothing could be more complete than the change that occurred in my emotions since the night the demon appeared. Before, I had viewed my promise with gloomy despair as something that had to be fulfilled regardless of the consequences. But now, I felt as if the blinders had been taken off my eyes and I was seeing clearly for the first time.",
    "The thought of resuming my work did not cross my mind for a single moment. The threat I had heard weighed down my thoughts, but I did not think that any voluntary action of mine could prevent it. I resolved in my heart that creating another being like the demon I first made would be an act of the most despicable and heinous selfishness, and I banished from my mind all thoughts that could lead to any other conclusion.",
    "The moon rose between two and three in the morning. I put the basket in a small boat and sailed out about four miles from the coast. The scenery was perfectly solitary.",
    "A few boats were returning toward the shore, but I steered away from them. I felt as if I were on my way to commit a terrible crime, and in chilling anxiety, I avoided encountering my fellow humans. The once-clear moon was suddenly covered by dark clouds, and seizing that moment of darkness, I threw the basket into the sea.",
    "I listened to the gurgling sound the basket made as it sank, and then sailed far away from that spot. The sky was covered with clouds, and though the air was cold from the northeast wind blowing at the time, it was clear. However, it refreshed me and filled me with such a pleasant sensation that I decided to extend my stay on the water, fixed the rudder straight, and stretched my body out on the bottom of the boat.",
    "Clouds hid the moon, everything was vague, and only the sound of the boat's keel cutting through the waves could be heard. That whispering soothed me, and I soon fell into a deep sleep.",
    "I do not know how long I remained in this state, but when I woke up, the sun had already risen quite high. The wind was blowing strongly, and the waves constantly threatened the safety of my little boat.",
    "I realized that the wind was a northeaster, and that it must have pushed me far away from the shore I had departed from. I tried to change my course, but I quickly realized that if I tried again, the boat would instantly fill with water.",
    "In this situation, the only thing I could do was to drive on against the wind. I confess I felt a bit of terror.",
    "I had no compass, and my knowledge of the geography of this area was so shallow that the sun was of little help. I might be swept out into the vast Atlantic and feel all the tortures of starvation, or be swallowed up into the unfathomably deep water howling and crashing around me.",
    "Having already been out at sea for several hours, I felt the torture of a burning thirst, the prelude to my other sufferings. I looked at the sky, where clouds blew along with the wind only to be replaced by others. I looked at the sea. That place would be my grave.",
    "\"Demon,\" I cried out. \"Your task is already done!\" I thought of Elizabeth, my father, and Clerval. All those left behind, upon whom the monster might satisfy his bloodthirsty and ruthless passion. This thought plunged me into such a despairing and terrifying fantasy that even at this moment, as the scene before me is about to close forever, I get goosebumps just thinking about it.",
    "A few hours passed like that. But gradually, as the sun leaned toward the horizon, the wind died down into a gentle breeze and the breaking waves disappeared from the sea. However, a massive swell took their place. When I felt nauseous and could hardly hold the rudder, I suddenly saw a ridge of high land to the south.",
    "To me, nearly exhausted from the fatigue and terrible anxiety I had endured for hours, this sudden certainty of life rushed into my heart like a warm flood of joy, and tears poured from my eyes.",
    "How fickle our emotions are. And how strange our love clinging to life even in the midst of terrible misfortune is! I made another sail out of some of my clothes and desperately turned the boat toward the land. The place looked rough and rocky, but as I got closer I could easily recognize signs of cultivation.",
    "I saw boats near the shore, and suddenly realized I had returned to the neighborhood of civilized people. I carefully followed the winding curves of the land, and finally cheered when I saw a spire rising from behind a small cape.",
    "Because I was extremely weakened, I decided to sail straight toward the village where I could most easily find food. Fortunately, I had money on me. As I rounded the cape, I saw a neat little town and an excellent harbor, and I entered it, feeling my heart pound with joy at my unexpected escape.",
    "As I was busy anchoring the boat and arranging the sails, several people flocked to the spot. They seemed very surprised by my appearance, but without offering me any help, they whispered among themselves, mixing in gestures that normally would have raised mild alarm in me.",
    "However, I only noticed that they were speaking English, so I addressed them in that language. \"Good friends,\" I said. \"Would you kindly tell me the name of this town and where I am right now?\"",
    "\"You will find out soon enough.\" answered a man with a hoarse voice. \"You may have come to a place that doesn't quite suit your tastes, but I assure you that we won't ask for your opinion on where you'll stay.\"",
    "I was very surprised to hear such a rude reply from a stranger, and I was even more bewildered when I saw the frowning and angry expressions of his companions. \"Why do you answer so bluntly?\" I replied.",
    "\"It surely isn't the custom of English people to welcome strangers so ungenerously.\"",
    "\"I don't know what the customs of the English are,\" the man said. \"But hating villains is the custom of the Irish.\"",
    "As this bizarre conversation continued, I noticed the crowd growing rapidly. Their faces were a mix of curiosity and anger, and I became somewhat anxious while also feeling annoyed. I asked for the way to the inn, but no one answered.",
    "Then, as I moved forward, a murmur arose from the crowd that followed and surrounded me. Just then, a rough-looking man approached, tapped me on the shoulder, and said. \"Look here, you'll have to go to Mr. Kirwin's house and explain yourself.\"",
    "\"Who is Mr. Kirwin? Why do I have to explain myself?",
    "Isn't this a free country?\"",
    "\"That's right, it's free enough for honest people. Mr. Kirwin is a magistrate.",
    "You will have to explain the death of a gentleman who was found murdered here last night.\"",
    "This answer startled me, but I soon regained my composure. I was innocent, and that could easily be proven. So I followed the guide in silence and was led to one of the best houses in the village.",
    "I was on the verge of collapsing from exhaustion and hunger, but since I was surrounded by a crowd, I thought it wise to squeeze out all my strength so that my physical weakness wouldn't be interpreted as fear or guilt. At that time, I never anticipated the disaster that would soon strike me and erase all fear of disgrace or death in terror and despair.",
    "I must pause here, for it requires all my patience to bring back the memory of the terrible events I am about to recount, in proper detail, into my mind."
]

file_path = 'c:/git_repo/Book_apps/frankenstein/src/main/assets/books/ch_24.json'
with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

for i in range(len(data)):
    if i < len(new_en):
        data[i]['en'] = new_en[i]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Replacement complete.")
