import json
import os

filepath = r"c:\git_repo\Book_apps\frankenstein\src\main\assets\books\ch_15.json"

updates = {
    1: "Chapter 11",
    2: "It is quite difficult to remember the earliest period of my existence; all the events of that time appear confusing and dim.",
    3: "Strange and diverse sensations seized me all at once, and I saw, felt, heard, and smelled at the same time. Truly, it took quite a long time before I learned to distinguish the operations of my various senses. Gradually, I remember having to close my eyes because a more intense light pressed upon my nerves.",
    4: "Then darkness came over me and made me anxious. But as soon as I felt that sensation, I opened my eyes, and looking back now, the light poured in upon me again.",
    5: "I walked, and perhaps I went downward. But I soon discovered a great change in my senses. Previously, dark and opaque objects had surrounded me, so I could neither touch nor see them, but now I found that I could wander freely without any obstacles that I could not either climb over or avoid.",
    6: "The light seemed to suppress me more and more, and the heat exhausted me as I walked, so I looked for a place where I could find shade. That place was the forest near Ingolstadt. There I lay by a stream to relieve my fatigue, and soon I felt the pain of hunger and thirst.",
    7: "This sensation woke me from my nearly sleeping state, and I found and ate berries hanging on trees or fallen on the ground. After quenching my thirst with the stream water, I lay down again and fell asleep.",
    8: "\"It was dark when I woke up. I felt cold, and I was instinctively half terrified by the fact that I was left so alone.",
    9: "Before leaving your apartment, I felt cold and wrapped myself in some clothes, but they were far from enough to protect me from the night dew. I was a pitiful, helpless, and miserable being.",
    10: "I knew nothing, and I could distinguish nothing. Just feeling pain invade me from all sides, I sat down and cried.",
    11: "\"Not long after, a gentle light spread across the sky and gave me a pleasant sensation. I jumped up and saw a dazzling figure rising through the trees.",
    12: "It was the moon. I looked at it with a kind of wonder. It moved slowly, but it lit my path, and I went out again to find berries.",
    13: "Still feeling cold, I found a large coat under a tree, wrapped my body in it, and sat down on the ground. There were no clear ideas in my mind, and everything was confusing.",
    14: "I felt light, hunger, thirst, and darkness. Countless sounds echoed in my ears, and various smells greeted me from all sides. The only object I could distinguish was the bright moon, and I fixed my eyes on it in joy.",
    15: "\"When day and night had crossed a few times and the night's heavenly body had greatly shrunk, I began to distinguish my senses from one another. Gradually, I clearly saw the clean stream that supplied me with drinking water and the trees that cast shade on me with their thick leaves. When I first discovered that the gentle sounds that often pleased my ears came from the throats of the small winged animals that often blocked the light from my vision, I was very happy.",
    16: "I also began to observe the shapes surrounding me more accurately and to recognize the boundaries of the radiant roof of light covering me. Sometimes I tried to imitate the joyful songs of the birds, but I could not. Sometimes I wanted to express my senses in my own way, but I was startled by the bizarre and unclear sounds that burst from my mouth and fell back into silence.",
    17: "\"Even until the moon disappeared from the night sky and reappeared in a smaller size, I still remained in the forest. By this time, my senses had become clear, and my mind accepted new ideas every day.",
    18: "My eyes became used to the light and to recognizing the proper shapes of objects. I came to distinguish insects from grass, and gradually one type of grass from another. I learned that sparrows only made harsh sounds, while the sounds of blackbirds and thrushes were sweet and fascinating.",
    19: "\"One day, suffering from the cold, I found a fire left behind by wandering beggars and felt joy at the warmth radiating from it. Out of joy, I thrust my hand into the burning charcoal, but hurriedly pulled it out with a scream of pain.",
    20: "I thought it was truly a strange thing. To think the same cause could produce such opposite results! I examined the material of the fire, and to my joy, I found that it was made of wood.",
    21: "I quickly gathered branches, but they were wet and would not burn. Disappointed by this, I sat still and watched how the fire worked. The wet wood I had placed near the heat dried out and caught fire on its own.",
    22: "I thought about this deeply, and by touching various branches, I discovered the cause. Then I moved busily to gather a large amount of wood and dry it so I could supply the fire plentifully. When night came and sleepiness swept over me, my greatest fear was that my fire would go out.",
    23: "I carefully covered the fire with dry wood and leaves and placed wet branches on top of it. Then I spread my coat, lay down on the ground, and fell asleep.",
    24: "\"When I woke up it was morning, and my first concern was checking the fire. When I removed the covering, a gentle breeze quickly fanned the embers and brought up a flame. I observed this too, and I made a fan out of branches to revive the almost dying embers.",
    25: "When night came again, I happily discovered that the fire provided not only heat but also light, and that the discovery of this element was useful for my food as well. I found that some of the scraps left by the travelers had been roasted in the fire, and they tasted much better than the berries picked from the trees. So I tried to cook my food in the same way by placing it over the burning charcoal.",
    26: "I found that the berries were ruined in this process, but the nuts and root vegetables tasted much better.",
    27: "\"However, food became increasingly scarce, and I often wandered the forest all day in vain to find a few acorns to soothe the pain of hunger. Realizing this situation, I decided to leave the place where I had lived so far to find a place where I could more easily satisfy my few needs. During this migration, I deeply regretted losing the fire I had accidentally obtained, but I did not know how to recreate it.",
    28: "I seriously pondered this difficulty for hours, but eventually I had to give up all attempts to supply the fire. I wrapped my body in my coat and walked across the forest toward the setting sun. After spending three days in such wandering, I finally discovered a wide open country area.",
    29: "It had snowed heavily the night before, so the fields were a bright white all over. The scenery looked bleak, and my feet felt like they were freezing because of the cold, wet substance covering the ground.",
    30: "\"It was around seven in the morning, and I desperately wanted food and a place to rest. Finally, on a rising hill, I found a small hut that must certainly have been built for the convenience of some shepherd. This was a new sight to me, and I examined the structure with great curiosity.",
    31: "Seeing the door open, I went inside. Inside, an old man was sitting by the fire preparing breakfast.",
    32: "He turned his head upon hearing a sound, and when he saw me, he screamed loudly and ran out of the hut. He fled across the field at a speed that seemed utterly impossible for his frail body. His appearance, which was different from any being I had ever seen before, and his fleeing behavior somewhat startled me.",
    33: "But I was fascinated by the appearance of the hut. Snow and rain could not leak in here, the ground was dry, and it looked like an exquisite and divine shelter to me, just as Pandemonium had provided to the demons suffering in the lake of fire in hell.",
    34: "I devoured the shepherd's leftover breakfast. It was bread, cheese, milk, and wine, but the wine did not suit my taste. Then, exhausted by fatigue, I lay down among the straw and fell asleep.",
    35: "\"It was noon when I woke up. Drawn to the warmth of the sun shining brightly over the white ground, I decided to begin my journey again. I packed the scraps of the farmer's leftover breakfast into a sack I found, and I advanced across the fields for hours until I arrived at a village around sunset.",
    36: "How miraculous this sight seemed! The huts, slightly neater houses, and fine mansions drew my admiration one after another.",
    37: "Seeing the vegetables in the gardens and the milk and cheese placed by the windows of some huts sparked my appetite. I went into one of the houses that looked the best among them.",
    38: "But as soon as I crossed the threshold, the children screamed and one of the women fainted. The whole village was turned upside down.",
    39: "Some fled, and some attacked me. Finally, severely injured by stones and many other kinds of thrown weapons, I fled to the wide open country and, trembling in great fear, took shelter in a low, empty, and humble shed. It was a truly miserable sight compared to the palace-like houses I had seen in the village.",
    40: "However, this shed was connected to a neat and pleasant-looking cottage, but because of the bitter experience I had just gone through, I did not dare to step inside it. My shelter was built of wood, but the ceiling was so low that it was hard to even sit straight up.",
    41: "There was no wooden floor, and bare dirt formed the ground, but it was dry. And even though wind blew in through countless cracks, I found that it was a pleasant shelter to avoid the snow and rain.",
    42: "\"So I took shelter here and lay down, happy in the fact that I had found a refuge—even if it was miserable—from the harshness of the season, and from the even more frightening barbarity of humans. As soon as day broke, I crawled out of my doghouse-like spot, examined the adjacent cottage, and checked if I could keep staying in this dwelling I had found.",
    43: "It was located on the back of the cottage and surrounded by sides exposed to a pigpen and a clear puddle of water. One side was open, and I had crawled in through there.",
    44: "But now I blocked every crack where I could be seen from the outside with stones and wood. I did this so that I could move them to go out when needed. The only light I could enjoy was what came in through the pigpen, but that was enough for me.",
    45: "\"After organizing my dwelling like this and covering the floor with clean straw, I retreated inside. I saw the figure of a man in the distance, and because I remembered the treatment I suffered the night before too well, I could not entrust my fate to him. But first, for that day's food, I prepared a piece of rough bread I had swiped, and a cup that would allow me to drink the clear water flowing by my hideout more conveniently than drinking with my hands.",
    46: "The floor was slightly raised, so it stayed perfectly dry, and since it was adjacent to the cottage chimney, it was quite warm.",
    47: "\"With these preparations finished, I decided to stay in this shed until something happened that might change my mind. Compared to the bleak forest that was my previous dwelling, with its dripping branches and damp soil, that place was truly a paradise.",
    48: "I happily ate my breakfast and was just about to remove a plank to get some water. At that moment I heard footsteps, and peeking through a small crack, I saw a young woman passing in front of my shed with a bucket on her head. The girl was young and had a gentle manner, which was different from the villagers or farm maids I saw after that.",
    49: "However, she was dressed shabbily. A rough blue petticoat and a linen jacket were all she wore, and her blonde hair was just braided without any decorations.",
    50: "She looked patient yet sad. She disappeared from my sight, and about fifteen minutes later, she returned carrying the bucket, which was now half filled with milk.",
    51: "As she was walking, the weight seemed heavy for her, and a young man came out to meet her. A deeper despair showed on his face. He uttered a few sounds in a melancholy manner, took the bucket from her head, and headed to the cottage himself.",
    52: "She followed, and the two disappeared. Before long, I again saw the young man crossing the field behind the cottage with tools in his hands. The girl was also busy doing something inside and outside the house.",
    53: "\"While inspecting my dwelling, I found that one of the cottage windows used to take up a part of my dwelling, but it was filled with wood instead of glass. If I pressed my eye against one of these wooden boards, there was a small, barely noticeable crack through which I could just barely look inside. Through this crack, I saw a small, whitewashed, and clean but empty room with almost no furniture.",
    54: "In a corner near the stove, an old man sat leaning his head on both hands in a pitiful posture.",
    55: "The young girl was busy organizing the cottage, but soon she took something out of a drawer, moved her hands busily, and sat next to the old man. The old man picked up some instrument and began to play a sound sweeter than the voices of thrushes or nightingales.",
    56: "Even to me, a pitiful and miserable being who had never seen anything beautiful, it was such a lovely sight. The elderly countryman's silver hair and benevolent expression drew my respect, and the girl's gentle manner brought out my love.",
    57: "The old man played a sweet and sorrowful tune, and I saw that the performance drew tears from the eyes of his lovely companion. The old man did not notice this fact until she sobbed aloud. Then he made a few sounds, and the beautiful girl stopped what she was doing and knelt at his feet.",
    58: "The old man raised her up and gave a very warm and affectionate smile. I felt strange and overwhelming sensations of nature that I had never experienced from hunger or cold, warmth or food. It was an emotion mixed with pain and joy. Unable to handle these emotions, I stepped back from the window.",
    59: "\"Not long after, the young man returned carrying a load of firewood on his shoulder. The girl met him at the door, helped lighten his load, and took some of the firewood inside the cottage to put on the fire. Then she and the young man retreated to a corner of the cottage, and he showed her a large piece of bread and a slice of cheese.",
    60: "She seemed pleased, went out to the garden, dug up some roots and plants, washed them in water, and put them over the fire. After that, she continued working, and the young man went out to the garden and seemed busy digging and pulling up roots. After he spent about an hour on that work, the young woman joined him, and they went into the cottage together.",
    61: "\"Meanwhile, the old man was lost in thought, but when his companions appeared, he took on a more cheerful atmosphere, and they sat down and ate. The meal was finished quickly. The young woman was busy organizing the cottage again, and the old man strolled in the sunlight in front of the cottage for a few minutes, leaning on the young man's arm.",
    62: "Nothing was more beautiful than the contrast between these two wonderful beings. One was old, had silver hair, and benevolence and love shone on his face. The younger one had a slender and elegant build, and his features formed the most exquisite symmetry, but his eyes and attitude expressed extreme sadness and despair.",
    63: "When the old man returned to the cottage, the young man headed across the field carrying different tools from the ones he had used in the morning.",
    64: "\"Night soon fell, but to my great wonder, I found out that the cottage people had a way to extend the light by using candles. I was very glad that the joy of watching my human neighbors did not end just because the sun went down. Around evening, the young girl and her companion were doing various things I could not understand, and the old man picked up the instrument that made the divine sound that had fascinated me in the morning.",
    65: "As soon as he finished playing, the young man started not playing, but letting out a monotonous sound that resembled neither the harmony from the old man's instrument nor the songs of the birds. It was a fact I learned later that he was reading a book aloud, but at that time I knew nothing about the science of words or letters.",
    66: "\"After spending some time like this, the family put out the lights and retreated, I guess, to get some rest.\""
}

with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    item_id = item.get('id')
    if item_id in updates:
        item['en'] = updates[item_id]

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
