import json

file_path = r'c:\git_repo\Book_apps\frankenstein\src\main\assets\books\ch_20.json'
with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

translations = {
    1: 'Chapter 16',
    2: '"Cursed, cursed creator!',
    3: 'Why did I have to live?',
    4: 'Why didn\'t I extinguish the spark of existence that you so irresponsibly granted in that instant?',
    5: 'I do not know. Despair had not yet seized me, and my feelings were only of anger and revenge.',
    6: 'I could gladly have destroyed the cottage and its inhabitants, and filled my stomach with their screams and misery.',
    7: '"When night fell, I left my hiding place and wandered in the forest; free from the fear of discovery, I burst out my agony with terrifying howls.',
    8: 'I was like a wild beast that had broken free from a trap, smashing things that blocked me and roaming the forest with the speed of a stag.',
    9: 'Oh! What a miserable night I spent!',
    10: 'The cold stars shone as if mocking me, and the bare trees waved their branches above my head; occasionally, the sweet voice of a bird burst forth amidst the silence.',
    11: 'Everything except me was resting or enjoying pleasure. Harboring hell inside me like the arch-fiend, I was furious at my situation of receiving no one\'s sympathy, and I wanted to uproot the trees, cover the surroundings in a complete mess and destruction, and then sit down and enjoy the ruins.',
    12: '"But this was a sensory luxury that could not last long. I was exhausted from excessive physical exertion and collapsed onto the damp grass in the sick helplessness of despair.',
    13: 'Out of the countless people existing in the world, there was no one who would pity or help me. Yet, should I feel kindness toward my enemies?',
    14: 'No. From that moment, I declared eternal war against humanity, and above all, against the one who created me and sent me out into this unbearable suffering.',
    15: '"The sun rose, and because I heard people\'s voices, I knew it was impossible to return to my hiding place during the day. Therefore, I hid my body in the thick bushes and decided to devote the next few hours to reflecting on my situation.',
    16: '"The pleasant sunshine and the clear daytime air restored me to some level of calmness, and when I thought about what had happened at the cottage, I couldn\'t help but believe that my conclusion had been too hasty. I had certainly acted rashly.',
    17: 'It was obvious that my conversation had caught the father\'s interest toward me, and it was foolish to expose my appearance to his children\'s horror. I should have made the old man De Lacey familiar with me, and when the children were ready to accept my approach, gradually revealed myself to the rest of the family.',
    18: 'However, I did not believe my mistake was irreversible, and after deep consideration, I decided to return to the cottage, find the old man, and win him over to my side with my explanation.',
    19: '"These thoughts calmed me down, and when afternoon came, I fell into a deep sleep. But the heat of my blood did not allow for peaceful dreams.',
    20: 'The terrible scene from the day before kept unfolding right before my eyes. The women were fleeing, and the furious Felix was tearing me away from his father\'s feet.',
    21: 'I woke up exhausted, and realizing it was already night, I crawled out of my hiding place and set out to find something to eat.',
    22: '"Having satisfied my hunger, I turned my steps toward the familiar path leading to the cottage. Everything there was peaceful. I crawled into my hiding place and silently waited, expecting the family\'s usual waking hour.',
    23: 'That time passed, and the sun rose high in the sky, but the cottage people did not appear. I trembled violently, afraid of a terrible misfortune.',
    24: 'Inside the cottage was dark, and no movement could be heard. I cannot explain the pain of this suspense.',
    25: '"After a while, two villagers passed by, stopped near the cottage, and had a conversation with fierce gestures. However, because they used the local language, which was different from the language of my protectors, I could not understand what they were saying.',
    26: 'But soon, Felix approached with another man. Knowing that he hadn\'t left the cottage that morning, I was surprised, and anxiously waited to find out the meaning of this unusual appearance from his story.',
    27: '"His companion said to him, \'Consider the fact that you will have to pay three months\' rent and lose the crops in the garden. I do not want to take an unfair advantage, so I hope you will take a few days to think about it and decide.\'',
    28: '"\'It\'s absolutely useless,\' Felix replied. \'We can never live in this cottage again. Because of that terrible incident I told you about, my father\'s life is in the greatest danger.',
    29: 'My wife and my sister will never recover from that horror. Please do not argue with me anymore. Take your house and let me flee from this place.\'',
    30: '"Felix, who was saying this, was trembling violently. He and his companion went into the cottage, stayed for a few minutes, and then left. I never saw any of the De Lacey family again.',
    31: '"I spent the rest of that day in my hiding place in a state of complete and stupid despair. My protectors had left and broken the only link that connected me to the world. For the first time, feelings of revenge and hatred filled my chest, and I did not try to control them, letting myself be swept away by the rapids, directing my mind toward injury and death.',
    32: 'When I thought of my friends, De Lacey\'s gentle voice, Agatha\'s affectionate eyes, and the Arabian\'s outstanding beauty, these thoughts disappeared and pouring tears somewhat soothed me. But when the thought returned that they had driven me out and abandoned me, anger, a rage of anger, returned, and since I could not hurt any human, I turned my fury to inanimate objects. As the night deepened, I placed various flammable materials around the cottage, and after destroying all traces of cultivation in the garden, I waited with forced impatience until the moon set and I could start my operation.',
    33: '"As the night deepened, a fierce wind blew from the forest and quickly scattered the clouds lingering in the sky. The gust raged like a massive avalanche, causing a kind of madness in my mind that broke down all boundaries of reason and reflection.',
    34: 'I set fire to a dry branch and danced furiously around the abandoned cottage, with my eyes fixed on the western horizon, right at the edge where the moon was almost touching.',
    35: 'A part of the sphere finally hid, and I waved my kindling. As it sank, I screamed loudly and set fire to the straw, heather, and bushes I had gathered.',
    36: 'The wind fanned the fire, and the cottage was quickly engulfed by flames that licked at it with split, destructive tongues.',
    37: '"As soon as I was sure that no rescue could save any part of the dwelling, I left the scene and headed into the forest to find a refuge.',
    38: '"And now, with the vast world before me, where should I turn my steps? I decided to fly far away from the scene of misfortune, but to me, hated and despised, every country must be equally terrible. Finally, the thought of you crossed my mind.',
    39: 'I learned from your documents that you are my father and creator. Who could I approach more appropriately than the one who gave me life?',
    40: 'Geography was not missing from the lessons Felix gave Safie. I learned the relative locations of various countries on Earth from them. You mentioned Geneva as the name of your hometown, and I decided to head there.',
    41: '"But how should I set my direction? I knew I had to travel southwest to reach my destination, but the sun was my only guide. I didn\'t know the names of the cities I would pass through, and I couldn\'t ask a single human for directions, but I did not despair.',
    42: 'Even though I felt nothing but hatred toward you, I could only hope for salvation from you. Heartless and unfeeling creator! You gave me perception and passion, and then threw me out to be an object of mockery and horror for humanity.',
    43: 'However, you were the only one I could demand compassion and compensation from, and I decided to seek from you the justice I had tried in vain to get from any other being in human form.',
    44: '"My journey was long, and the pain I suffered was intense. It was late autumn when I left the area I had stayed in for so long. I only traveled at night, afraid of running into a human face.',
    45: 'The nature around me decayed, and the sun lost its warmth. Rain and snow poured down, and massive rivers froze. The surface of the earth was hard, cold, and bare, and I could not find a shelter.',
    46: 'Oh, Earth! How often did I hurl curses at the cause of my existence! The gentleness of my nature disappeared, and everything inside me turned into bile and bitterness.',
    47: 'The closer I got to your dwelling, the more deeply I felt the spirit of revenge burning in my heart. Snow fell and water hardened, but I did not rest. A few occasional events guided my way, and I had a map of the region, but I often lost my way and wandered far.',
    48: 'The pain of my emotions gave me no time to rest. No event occurred from which my anger and misery could not draw their food. However, when the sun regained its warmth and the earth began to look green again, an incident that happened when I reached the Swiss border confirmed the bitterness and horror of my feelings in a special way.',
    49: '"I usually rested during the day and traveled only at night when I was safe from human eyes. However, one morning, discovering that my path passed through a deep forest, I dared to continue traveling even after the sun had risen. That day, which was one of the first days of spring, made even me feel good with the loveliness of the sunlight and the freshness of the air.',
    50: 'I felt the emotions of gentleness and joy, which seemed to have been dead for a long time, revive inside me. Half surprised by the novelty of this sensation, I gave myself up to it, and daring to forget my solitude and deformity, I tried to be happy. Soft tears wet my cheeks again, and I even lifted my moist eyes to thank the blessed sun that gave me such joy.',
    51: '"I continued winding along the forest path, and finally reached a deep and fast river border lined with many trees that were sprouting buds and drooping their branches in the fresh spring.',
    52: 'Stopping here, not knowing exactly which way to go, I heard the voice of a young girl running toward my hiding place in the forest, laughing as if playing a prank and running away, so I hid my body under the shade of a cypress tree. As soon as I hid, the girl ran toward me.',
    53: 'She continued running along the steep bank of the river, and suddenly her foot slipped and she fell into the fierce river water. I rushed out of my hiding place, and paying an extreme effort because of the current\'s force, rescued her and pulled her to the shore.',
    54: 'She lost consciousness, and as I was struggling to revive her with every method I could, I was interrupted by the approach of a villager, who seemed to be the person she had playfully run away from. Seeing me, he rushed at me, snatched the girl from my arms, and hurried away toward the deeper part of the forest.',
    55: 'Without knowing why, I quickly chased after him. However, seeing me approach, the man aimed the gun he was carrying at my body and fired. I collapsed to the ground, and the one who hurt me quickened his pace and fled into the forest.',
    56: '"Was this the reward for my good deed! I saved a human from ruin, and as a reward, I was now writhing in the miserable pain of a wound that shattered my flesh and bones. The feelings of kindness and gentleness I had harbored just a few minutes ago turned into hellish anger and teeth grinding.',
    57: 'Burning with pain, I swore eternal hatred and revenge against all humanity. However, the pain of the wound overwhelmed me, my pulse stopped, and I fainted.',
    58: '"For a few weeks, I lived a miserable life in the forest, struggling to treat the wound I had received. A bullet was lodged in my shoulder, and I couldn\'t tell if it remained there or had passed through. Anyway, I had no way to take it out.',
    59: 'My suffering grew even larger because of the oppressive sense of the unfairness and ingratitude of their harm. My daily vows surged for revenge. A deep and fatal revenge, the kind of revenge that could uniquely compensate for the humiliation and agony I had endured.',
    60: '"After a few weeks, the wound healed, and I continued my journey. The hardships I endured were no longer relieved by the bright sun or soft spring breeze. All joy was merely a mockery that insulted my desolate state and made me feel even more keenly that I was not made to enjoy pleasure.',
    61: '"But now my toil was coming to an end, and two months from this time, I arrived on the outskirts of Geneva.',
    62: '"It was around evening when I arrived, and I retreated to a hiding place in one of the fields surrounding Geneva to ponder how to approach you. Crushed by fatigue and hunger, I was too unhappy to enjoy the gentle evening breeze or the scenery of the sun setting behind the massive Jura mountains.',
    63: '"At this time, a light sleep freed me from the pain of reflection, but I was awakened by the approach of a beautiful child who ran to the corner I had chosen with all the playfulness of childhood. Suddenly staring at him, the thought struck me that this little creature had no prejudice and had lived too short a time to absorb the horror of deformity. Therefore, I thought that if I could catch him and educate him as my companion and friend, I would not be so lonely on this heavily populated earth.',
    64: '"Driven by this urge, I grabbed the passing boy and pulled him toward me.',
    65: 'As soon as he saw my appearance, he covered his eyes with his hands and let out a sharp scream. I forcefully pulled his hands away from his face and said. \'Child, what does this mean?',
    66: 'I have no intention of hurting you. Listen to me.\'',
    67: '"He fiercely resisted. \'Let me go,\' he shouted. \'Monster!',
    68: 'Ugly wretch! You want to eat me and tear me to pieces. You\'re an ogre.',
    69: 'Let me go, or I\'ll tell my dad.\'',
    70: '"\'Boy, you will never see your dad again. You have to come with me.\'',
    71: '"\'Hideous monster! Let me go.',
    72: 'My dad is a magistrate. He\'s Mr. Frankenstein. My dad will punish you.',
    73: 'You can\'t keep me.\'',
    74: '"\'Frankenstein! If so, you belong to my enemy, the one to whom I swore eternal revenge. You will be my first victim.\'',
    75: '"The child continued to struggle, hurling insults that brought despair to my heart. I grabbed his neck to silence him, and a moment later he lay dead at my feet.',
    76: '"I stared at the victim, and my chest swelled with joy and a hellish sense of triumph. I clapped my hands and shouted. \'I too can create ruin.',
    77: 'My enemy is not invulnerable. This death will bring him despair, and thousands of other misfortunes will torment and destroy him.\'',
    78: '"When I fixed my eyes on the boy, I saw something shiny on his chest. I took it. It was a portrait of a very lovely woman.',
    79: 'Despite my malice, it made me gentle and captivated me.',
    80: 'For a moment, I joyfully gazed at the dark eyes bordered by deep eyelashes and the lovely lips. But soon, the anger returned. I remembered that I was forever deprived of the joy such beautiful creatures could provide, and the fact that she, who resembled the face I was gazing at, would change that look of divine kindness into an expression of disgust and terror if she saw me.',
    81: '"Are you surprised that these thoughts excited me with anger? Rather, it is a wonder that at that moment, instead of spewing out my senses in shouts and agony, I did not rush among humans and die in the attempt to destroy them.',
    82: '"Swept up in these emotions, I left the place where I committed the murder and entered a barn that looked empty while looking for a more secluded hiding place.',
    83: 'A woman was sleeping on top of some straw. She was young, and although not as beautiful as the woman in the portrait I was holding, she had a pleasant appearance and bloomed with the loveliness of youth and health.',
    84: 'Here, I thought, is one of those people who give a smile that brings joy to everyone except me.',
    85: 'And I bent over her and whispered. \'Wake up, fairest one. Your lover is near.',
    86: 'A person who would even give his life to get one affectionate look from your eyes. My love, wake up!\'',
    87: '"The sleeping person tossed and turned. A shudder of terror pierced through me.',
    88: 'What if she really wakes up, sees me, curses me, and accuses me of being a murderer? If her dark eyes open and she sees me, she will surely act that way.',
    89: 'The thought was madness. It stirred the fiend inside me. It won\'t be me, but she who will suffer. The murder I committed is because I am forever deprived of all that she could give me. She shall make amends for it.',
    90: 'The root of the crime lies with her, so the punishment must be hers too! Thanks to Felix\'s teachings and the cruel laws of humans, I have now learned how to commit evil deeds.',
    91: 'I bent over her and securely tucked the portrait into one of the folds of her dress. She moved again, and I fled.',
    92: '"For a few days, I roamed the place where these events occurred. Sometimes I wanted to see you, and sometimes I was determined to leave the world and its misery forever.',
    93: 'Finally, I wandered toward this mountain range, and roaming its massive valleys, I am possessed by a burning passion that only you can satisfy.',
    94: 'We cannot part until you promise to comply with my demand.',
    95: 'I am lonely and miserable. Humans will not associate with me. But a being as deformed and terrible as myself would not reject herself to me.',
    96: 'My companion must be of the same species and have the same flaws. You must create this creature."'
}

for item in data:
    if item['id'] in translations:
        item['en'] = translations[item['id']]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Updated JSON file successfully.')
