import json
import os

file_path = r'c:\git_repo\Book_apps\frankenstein\src\main\assets\books\ch_17.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

new_en = {
    1: "Chapter 13",
    2: "\"I will now hurry to the more touching part of my story. I will tell you about the events that gave me deep feelings and made me who I am today from who I used to be.",
    3: "\"Spring arrived quickly, the weather became sunny, and there wasn't a single cloud in the sky. It was very surprising that the place, which used to be bleak and gloomy, was now blooming with the most beautiful flowers and greenery. My senses were satisfied and brought back to life by a thousand wonderful scents and a thousand beautiful sights.",
    4: "\"That day was one of the days when the family took their regular break from work. The old man played the guitar and the children listened to his playing, and I noticed that Felix's face was indescribably gloomy. He sighed often, and once his father stopped playing, I guessed from the old man's attitude that he was asking the cause of his son's sadness. Felix answered in a cheerful tone, and when the old man was about to restart the music, someone knocked on the door.",
    5: "\"A woman on horseback arrived with a country guide. The woman wore dark clothes and covered her face with a thick black veil. When Agatha asked a question, the stranger answered by only saying Felix's name in a sweet accent.",
    6: "Her voice was like music, but it was different from my friends' voices. Hearing this word, Felix hurried over to the woman, and when she saw him, she lifted her veil, and I saw a face that was angelic and expressive. Her hair was as shiny black as a raven and strangely braided, and her eyes were black but soft and full of life. Her features were well-proportioned, her skin was amazingly white, and both of her cheeks were tinted with a lovely pink.",
    7: "\"Felix looked ecstatic when he saw her, all trace of sadness disappeared from his face, and he immediately showed feelings of ecstatic joy. I could hardly believe he could have such feelings. His eyes sparkled as his cheeks turned red with joy, and in that moment I thought he was as beautiful as that strange woman. She seemed to be overwhelmed by other emotions; she wiped a few tears from her beautiful eyes and reached out her hand to Felix. He kissed her hand passionately and, as far as I could understand, called her his sweet Arabian.",
    8: "She did not seem to understand his words, but she smiled. He helped her get off the horse, sent the guide away, and led her into the cabin. A conversation took place between him and his father, and the young stranger knelt at the old man's feet and tried to kiss his hand, but he raised her up and hugged her affectionately.",
    9: "\"I soon realized that although the strange woman made clear sounds and seemed to have her own language, she wasn't understood by the people in the cabin, nor did she understand them herself. They sent many signals that I did not understand, but I saw that her presence spread joy throughout the cabin, driving away their sadness like the sun clearing the morning fog. Felix looked especially happy and welcomed his Arabian with a joyful smile.",
    10: "The always gentle Agatha kissed the lovely stranger's hands and pointed to her brother, sending a signal that seemed to mean he had been sad until she came. A few hours passed like this, and they expressed a joy with their facial expressions that I did not know the cause of. Soon, as I frequently heard a certain sound that the strange woman repeated after them, I realized that she was trying to learn their language, and the thought immediately came to me that I too should use the same lessons for the same purpose.",
    11: "The strange woman learned about twenty words in her first lesson. In fact, most of them were words I already knew, but I benefited from the other words.",
    12: "\"As night approached, Agatha and the Arabian went to bed early. When they parted, Felix kissed the strange woman's hand and said, 'Good night, lovely Safie.' He stayed up much later talking with his father, and hearing her name repeated often, I guessed that their lovely guest was the topic of conversation.",
    13: "I was consumed by a passionate desire to understand them and poured all my abilities into that goal, but I found out that it was completely impossible.",
    14: "\"The next morning Felix went out to work, and after Agatha's daily chores were finished, the Arabian sat at the old man's feet, took his guitar, and played a melody so enchantingly beautiful that tears of both sadness and joy flowed from my eyes. She sang, and her voice flowed with rich accents, swelling or fading like a nightingale in the woods.",
    15: "\"After she finished singing, she gave the guitar to Agatha, who initially refused. She played a simple melody and her voice accompanied it with a sweet accent, but it was different from the strange woman's wonderful tune. The old man seemed captivated and said a few words that Agatha tried hard to explain to Safie, which seemed to convey the meaning that her music gave him the greatest joy.",
    16: "\"Now the days passed as peacefully as before, and the only change was that joy had taken the place of sadness on my friends' faces. Safie was always cheerful and happy. She and I improved quickly in our knowledge of the language, and two months later we began to understand most of the words my protectors said.",
    17: "\"During this time, the black earth was also covered with grass, and countless flowers bloomed on the green banks to delight the scent and the eyes, like pale shining stars among the moonlit woods. The sun grew warmer, and the nights were clear and refreshing. My night walks were a great joy to me, even though they were quite shortened by the sun setting late and rising early. I never dared to go outside during the day, for fear of receiving the same treatment I had previously experienced in the first village I entered.",
    18: "\"My days were spent paying close attention to learn the language faster. And I can boast that I progressed more quickly than the Arabian. She understood very little and spoke with a clumsy accent, but I could understand and imitate almost every word I heard.",
    19: "\"As my speaking skills improved, I also learned the science of writing that was taught to the strange woman, and this opened a wide field of wonder and joy before me.",
    20: "\"The book Felix used to teach Safie was Volney's 'Ruins of Empires'. If Felix had not given very detailed explanations while reading the book, I would not have understood its meaning. He said he chose this book because the eloquent style was composed as an imitation of Eastern writers.",
    21: "Through this work, I gained superficial knowledge about history and a perspective on the various empires currently existing in the world. It gave me insight into the customs, governments, and religions of various countries on Earth. I heard about lazy Asians, the wondrous genius and mental activity of the Greeks, the wars and amazing virtues of the early Romans, their subsequent corruption, the decline of that massive empire, chivalry, Christianity, and kings.",
    22: "I heard about the discovery of the American continent and shed tears with Safie over the unfortunate fate of its natives.",
    23: "\"These amazing stories filled me with unfamiliar emotions. Could humans truly be so powerful, so virtuous and magnificent, while at the same time being so evil and base? At one time they seemed like mere descendants of the principle of evil, and at another time they appeared as everything one could imagine of a noble, godlike being.",
    24: "Becoming a great and virtuous person seemed like the highest honor that could happen to a sentient being, and becoming base and evil, like many recorded in history, seemed like the lowest corruption, a state more miserable than a blind mole or a harmless bug. For a long time, I couldn't imagine how a human could set out to murder his own kind, or even why laws and governments exist. But when I heard the detailed stories of evil deeds and bloodshed, my wonder stopped and I turned away in disgust and hatred.",
    25: "\"Now the cabin people's conversations opened new wonders to me. While listening to the teachings Felix bestowed on the Arabian, the bizarre human social system was explained to me. I heard about the division of property, immense wealth and miserable poverty, class, lineage, and noble blood.",
    26: "\"Those words made me look back at myself. I learned that the possession your kind respects the most is a high and pure lineage combined with wealth. A person can be respected even with only one of these two advantages, but if they lack both, except in very rare cases, they were considered vagabonds and slaves doomed to waste their abilities for the benefit of a chosen few! Then what am I?",
    27: "I was completely ignorant about my creation and my creator, but I knew that I had no money, no friends, and no property of any kind. Furthermore, I had a terribly deformed and disgusting appearance. I wasn't even of the same nature as a human.",
    28: "I was more agile than them and could survive on rougher food. I endured extreme heat and cold while taking fewer injuries to my body. My height far exceeded theirs. When I looked around, I never saw or heard of a being like me. Then am I a stain on the earth, a monster that everyone avoids and everyone denies?",
    29: "\"The pain these thoughts brought me is indescribable. I tried to shake them off, but as my knowledge grew, only my sadness increased. Oh, if only I had stayed in my home forest forever, if only I had known and felt nothing except the sensations of hunger, thirst, and heat!",
    30: "\"What a bizarre nature knowledge has! Like lichen on a rock, once it settles in the mind, it does not fall off. Sometimes I wanted to shake off all thoughts and feelings, but I learned that the only way to overcome the sensation of pain was death. Death was a state that I feared yet did not understand.",
    31: "I admired virtue and good feelings and loved my family's gentle attitude and sweet nature, but I was shut off from interacting with them except through means I secretly obtained when unseen and unknown, and that increased rather than satisfied my desire to become one of my kind. Agatha's kind words and the charming Arabian's lively smile were not for me.",
    32: "The old man's gentle advice and the beloved Felix's lively conversations were not for me. A miserable and unhappy wretch!",
    33: "\"Other lessons were engraved even more deeply in me. I heard about the difference in genders, the birth and growth of children, how a father is completely absorbed in an infant's smile and an older child's lively wit, how a mother's whole life and care are focused on that precious responsibility, how a young person's mind expands and acquires knowledge, and about brothers, sisters, and the various different relationships that bind a human being together in mutual ties.",
    34: "\"But where are my friends and relatives? No father watched over my childhood, and no mother blessed me with smiles and caresses. Even if they had, my past life was now a blind blank and a stain where I could distinguish nothing. From the earliest time I can remember, I was the same in height and proportions as I was then.",
    35: "I had never seen a being that looked like me or claimed to interact with me. What am I? That question came to mind again and was only answered with a groan.",
    36: "\"I will soon explain where these feelings came to lead, but for now please let me return to the cabin people. Their story brought up various emotions in me, such as anger, joy, and wonder, but all of that resulted in additional love and respect for my protectors—for I loved calling them that in an innocent and half-painful self-deception.\""
}

for item in data:
    if item['id'] in new_en:
        item['en'] = new_en[item['id']]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done updating file.")
